In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("C:\\Users\\Administrator\\Downloads\\Spotify\\spotify_history.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator\\Downloads\\Spotify\\spotify_history.csv'

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149860 entries, 0 to 149859
Data columns (total 11 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   spotify_track_uri  149860 non-null  object
 1   ts                 149860 non-null  object
 2   platform           149860 non-null  object
 3   ms_played          149860 non-null  int64
 4   track_name         149860 non-null  object
 5   artist_name        149860 non-null  object
 6   album_name         149860 non-null  object
 7   reason_start       149717 non-null  object
 8   reason_end         149743 non-null  object
 9   shuffle            149860 non-null  bool
 10  skipped            149860 non-null  bool
dtypes: bool(2), int64(1), object(8)
memory usage: 6.0+ MB

In [4]:
df["ts"] = pd.to_datetime(df["ts"])  #we converted the ts datatype to time object
#we fill all the missing values with blank
df["reason_start"] = df["reason_start"].fillna("Blank") 
df["reason_end"] = df["reason_start"].fillna("Blank")

In [11]:
# show the platform with the highest frequency
df["platform"].value_counts()

platform
android           139821
cast to device      3898
iOS                 3049
windows             1691
mac                 1176
web player           225
Name: count, dtype: int64

In [14]:
# count the unique number of artist name
df["artist_name"].nunique()

4113

In [16]:
# count the unique number of album 
df["album_name"].nunique()

7948

In [17]:
df["shuffle"].value_counts()

shuffle
True     111583
False     38277
Name: count, dtype: int64

In [18]:
df["skipped"].value_counts()

skipped
False    141991
True       7869
Name: count, dtype: int64

In [19]:
# working with date and time
df["year"] = df["ts"].dt.year
df["month"] = df["ts"].dt.month
df["day"] = df["ts"].dt.day
df["hour"] = df["ts"].dt.hour
df["minute"]= df["ts"].dt.minute
df["second"] = df["ts"].dt.second

In [20]:
df.head()

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped,year,month,day,hour,minute,second
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,autoplay,False,False,2013,7,8,2,44,34
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False,2013,7,8,2,45,37
2,487OPlneJNni3NWC8SYqhW,2013-07-08 02:50:24,web player,285386,Born To Die,Lana Del Rey,Born To Die - The Paradise Edition,clickrow,clickrow,False,False,2013,7,8,2,50,24
3,5IyblF777jLZj1vGHG2UD3,2013-07-08 02:52:40,web player,134022,Off To The Races,Lana Del Rey,Born To Die - The Paradise Edition,trackdone,trackdone,False,False,2013,7,8,2,52,40
4,0GgAAB0ZMllFhbNc3mAodO,2013-07-08 03:17:52,web player,0,Half Mast,Empire Of The Sun,Walking On A Dream,clickrow,clickrow,False,False,2013,7,8,3,17,52

In [21]:
df["year"].value_counts()

year
2017    26320
2020    24280
2021    22991
2022    16202
2019    14927
2018    14817
2023    11023
2024     9870
2016     6413
2015     2809
2013      185
2014       23
Name: count, dtype: int64

In [22]:
import plotly.express as px
fig = px.bar(df["year"].value_counts())
fig.show(renderer='iframe')
# fig.show(renderer='iframe_connected')
fig.show(renderer='colab')

In [24]:
df["hour"].value_counts()

hour
0     10884
23    10516
20    10494
1      9395
17     9194
2      9029
21     8953
18     8945
22     8715
3      8550
19     8165
6      7369
5      7164
16     6737
4      6355
7      4412
15     3725
14     2759
8      2312
9      1695
13     1658
10     1207
11      903
12      724
Name: count, dtype: int64

In [25]:
# hour with the most stream
fig = px.bar(df["hour"].value_counts())
fig.show(renderer='iframe')

In [26]:
df.groupby(["year", "month"])["day"].count().unstack().fillna(0)

month,1,2,3,4,5,6,7,8,9,10,11,12
year,,,,,,,,,,,,
2013,0.0,0.0,0.0,0.0,0.0,0.0,115.0,41.0,29.0,0.0,0.0,0.0
2014,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2015,23.0,0.0,0.0,0.0,0.0,121.0,33.0,956.0,710.0,803.0,82.0,81.0
2016,2.0,2.0,0.0,0.0,1.0,897.0,428.0,1051.0,434.0,404.0,538.0,2656.0
2017,2531.0,478.0,1576.0,1949.0,1625.0,1050.0,3915.0,3191.0,5176.0,2481.0,1255.0,1093.0
2018,1681.0,1125.0,785.0,926.0,1566.0,995.0,803.0,1446.0,1470.0,963.0,1862.0,1195.0
2019,567.0,289.0,749.0,1565.0,236.0,728.0,1622.0,2018.0,1339.0,2830.0,2059.0,925.0
2020,1227.0,1036.0,1591.0,2189.0,1609.0,1578.0,664.0,2668.0,2886.0,3263.0,3104.0,2465.0
2021,2635.0,2006.0,1629.0,2940.0,1875.0,2085.0,1161.0,1697.0,2169.0,1952.0,1072.0,1770.0
2022,1314.0,1670.0,1330.0,971.0,1187.0,1856.0,1695.0,883.0,1908.0,1615.0,1048.0,725.0
2023,1073.0,935.0,1018.0,1045.0,1400.0,846.0,865.0,854.0,650.0,777.0,785.0,775.0
2024,1449.0,924.0,700.0,619.0,569.0,524.0,318.0,932.0,962.0,1300.0,1425.0,148.0

In [27]:
fig = px.bar(df.groupby(["year", "month"])["day"].count().unstack().fillna(0))
fig.show(renderer='iframe')

In [29]:
df["artist_name"].value_counts()[:10]

artist_name
The Beatles           13621
The Killers            6878
John Mayer             4855
Bob Dylan              3814
Paul McCartney         2697
Led Zeppelin           2482
Johnny Cash            2478
The Rolling Stones     2390
Radiohead              2305
The Black Keys         2231
Name: count, dtype: int64

In [28]:

fig = px.bar(df["artist_name"].value_counts()[:10])
fig.show(renderer='iframe')

In [32]:
top_10_artists = df["artist_name"].value_counts()[:10].reset_index()
top_10_artists.columns = ["artist_name", "count"]
top_10_artists

          artist_name  count
0         The Beatles  13621
1         The Killers   6878
2          John Mayer   4855
3           Bob Dylan   3814
4      Paul McCartney   2697
5        Led Zeppelin   2482
6         Johnny Cash   2478
7  The Rolling Stones   2390
8           Radiohead   2305
9      The Black Keys   2231

In [68]:
import plotly.express as px

fig = px.bar(
    top_10_artists,
    x="artist_name",
    y="count",
    text="count"
)

# fig.update_traces(textposition='outside')  # place text outside bars
fig.show(renderer='iframe')

In [43]:
df[df["artist_name"]=="The Beatles"]["album_name"].unique()

array(['Magical Mystery Tour', 'Help!', '1', 'Abbey Road', 'Rubber Soul',
       'Please Please Me', 'The Beatles', 'Revolver',
       "A Hard Day's Night", 'Past Masters',
       "Sgt. Pepper's Lonely Hearts Club Band", 'Let It Be',
       'With The Beatles', 'Beatles For Sale',
       'Beatles For Sale - Remastered', 'Let It Be... Naked',
       'Live At The BBC', 'Get Back', 'Anthology 3', 'Yellow Submarine',
       'Anthology 1', 'Anthology 2', 'Now And Then'], dtype=object)

In [57]:
# df[df["artist_name"]=="The Beatles"]["album_name"] == "With The Beatles"
df[df["album_name"] == "With The Beatles"]["year"].value_counts(sort=False)

year
2016     34
2017    175
2018     98
2019     85
2020    110
2021     63
2022     33
2023     17
2024     19
Name: count, dtype: int64

In [58]:
df.head(2)

,spotify_track_uri,ts,platform,ms_played,track_name,artist_name,album_name,reason_start,reason_end,shuffle,skipped,year,month,day,hour,minute,second
0,2J3n32GeLmMjwuAzyhcSNe,2013-07-08 02:44:34,web player,3185,"Say It, Just Say It",The Mowgli's,Waiting For The Dawn,autoplay,autoplay,False,False,2013,7,8,2,44,34
1,1oHxIPqJyvAYHy0PVrDU98,2013-07-08 02:45:37,web player,61865,Drinking from the Bottle (feat. Tinie Tempah),Calvin Harris,18 Months,clickrow,clickrow,False,False,2013,7,8,2,45,37

In [63]:
year2013 = df[df["year"]== 2016]

In [73]:
year2013["artist_name"].value_counts()[:10].values

array([715, 216, 206, 189, 142, 141, 129, 129, 123, 114], dtype=int64)

In [65]:
year2024 = df[df["year"]== 2024]
year2024["artist_name"].value_counts()

artist_name
The Beatles        511
John Mayer         439
The Killers        423
ABBA               302
Paul McCartney     183
                  ...
Minutemen            1
Haunted Coffee       1
Hamid Al Shaeri      1
Jet                  1
Diego Torres         1
Name: count, Length: 1072, dtype: int64

In [74]:
import pandas as pd
import plotly.graph_objects as go


years = sorted(df['year'].unique())
fig = go.Figure()

# Create a trace for each year
for i, year in enumerate(years):
    top_artists = df[df["year"] == year]["artist_name"].value_counts().nlargest(10)

    fig.add_trace(go.Bar(
        x=top_artists.index,
        y=top_artists.values,
        name=str(year),
        visible=(i == 0)  # Show only the first year initially
    ))

# Create buttons for dropdown
buttons = [
    dict(label=str(year),
         method="update",
         args=[{"visible": [j == i for j in range(len(years))]},
               {"title": f"Top Artists in {year}"}])
    for i, year in enumerate(years)
]

# Update layout with dropdown
fig.update_layout(
    updatemenus=[dict(
        active=0,
        buttons=buttons,
        x=0.1,
        y=1.2
    )],
    title="Top Artists by Year",
    xaxis_title="Artist Name",
    yaxis_title="Count",
    showlegend=False
)

fig.show(renderer='iframe')

In [75]:
import pandas as pd
import plotly.graph_objects as go


years = sorted(df['year'].unique())
fig = go.Figure()

# Create a trace for each year
for i, year in enumerate(years):
    top_artists = df[df["year"] == year]["hour"].value_counts().nlargest(10)

    fig.add_trace(go.Bar(
        x=top_artists.index,
        y=top_artists.values,
        name=str(year),
        visible=(i == 0)  # Show only the first year initially
    ))

# Create buttons for dropdown
buttons = [
    dict(label=str(year),
         method="update",
         args=[{"visible": [j == i for j in range(len(years))]},
               {"title": f"Listen time in {year}"}])
    for i, year in enumerate(years)
]

# Update layout with dropdown
fig.update_layout(
    updatemenus=[dict(
        active=0,
        buttons=buttons,
        x=0.1,
        y=1.2
    )],
    title="listen time by Year",
    xaxis_title="Hours",
    yaxis_title="Count",
    showlegend=False
)

fig.show(renderer='iframe')

In [76]:
skipped =df[df["skipped"]==False]
skipped.groupby("artist_name")["day"].count().sort_values()

artist_name
Larkin Poe              1
Groovin' Bohemia        1
Paul Hindemith          1
Grizfolk                1
Grinderman              1
                    ...
Paul McCartney       2590
Bob Dylan            3651
John Mayer           4702
The Killers          6681
The Beatles         13233
Name: day, Length: 3825, dtype: int64